In [144]:
import pandas as pd
from sklearn.datasets import load_iris
iris=load_iris()

In [145]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     flower  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [146]:
df['flower']=df['flower'].apply(lambda x: iris.target_names[x])
df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [147]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(iris.data,iris.target,test_size=.3)

In [148]:
from sklearn import svm
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9555555555555556

In [149]:
from sklearn.model_selection import cross_val_score

In [150]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [151]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [152]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

import numpy as np
kernels=['rbf','linear']
C=[1,10,20]
avg_score={}
for kval in kernels:
    for cval in C:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[kval+'_'+str(cval)]=np.average(cv_scores)
        
avg_score



In [153]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel': ['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_
                 
    

{'mean_fit_time': array([0.01499929, 0.00258417, 0.00139546, 0.00099773, 0.00119753,
        0.00079045]),
 'std_fit_time': array([2.40638832e-02, 4.81039234e-04, 7.97749649e-04, 4.62310777e-07,
        3.99971037e-04, 3.95469967e-04]),
 'mean_score_time': array([0.00139666, 0.00161085, 0.00099721, 0.00039849, 0.00059824,
        0.00039907]),
 'std_score_time': array([1.01730794e-03, 4.70799478e-04, 5.35248383e-07, 4.88052035e-04,
        4.88460855e-04, 4.88753537e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [154]:
df3=pd.DataFrame(clf.cv_results_)
df3

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.014999  2.406388e-02         0.001397    1.017308e-03       1   
1       0.002584  4.810392e-04         0.001611    4.707995e-04       1   
2       0.001395  7.977496e-04         0.000997    5.352484e-07      10   
3       0.000998  4.623108e-07         0.000398    4.880520e-04      10   
4       0.001198  3.999710e-04         0.000598    4.884609e-04      20   
5       0.000790  3.954700e-04         0.000399    4.887535e-04      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [155]:
df3[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [156]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [157]:
clf.best_score_

0.9800000000000001

In [158]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [159]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
    },cv=5,return_train_score=False,
                        n_iter=2
                       )
rs.fit(iris.data,iris.target)
df4=pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
df4

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1       1          rbf         0.980000

In [160]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [161]:

model_params={
    'svm':{
    'model': svm.SVC(gamma='auto'),
    'params':{
        'C':[0,10,20],
        'kernel':['rbf','linear']
        }        
    },
    'random_forest':{
        'model': RandomForestClassifier(),
        'params':{
             'n_estimators':[1,5,10]
        }
    },
    'LogisticRegression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
           }
        }
    }


In [163]:

scores=[]
for model_name,mp in model_params.items():
    clf2=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf2.fit(iris.data,iris.target)
    scores.append({
        'model': model_name,
        'best_score':clf2.best_score_,
        'best_params':clf2.best_params_
        })

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 226, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 277, in _dense_fit
    self._probB, self.fit_status_ = libsvm.fit(
  File "sklearn\svm\_libsvm.pyx", line 192, in sklearn.svm._libsvm.fit
ValueError: C <= 0

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Est

In [164]:
df=pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                 best_params
0                 svm    0.980000  {'C': 10, 'kernel': 'rbf'}
1       random_forest    0.953333         {'n_estimators': 5}
2  LogisticRegression    0.966667                    {'C': 5}