In [1]:
import pandas as pd
df=pd.read_csv('D:\\data\\diabetics.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [2]:
import numpy as np

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
(df==0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [5]:
#GM=df['Glucose'].median()
#df['Glucose']=df['Glucose'].replace(0,GM)
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
#df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
#df['SkinThickness']=np.where(df['SkinThickness']==0,df['SkinThickness'].median(),df['SkinThickness'])
#df['BloodPressure']=np.where(df['BloodPressure']==0,df['BloodPressure'].median(),df['BloodPressure'])
#df['BMI']=np.where(df['BMI']==0,df['BMI'].median(),df['BMI'])

(df==0).sum()

Pregnancies                 111
Glucose                       0
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [6]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35        0  33.6   
1            1     85.0             66             29        0  26.6   
2            8    183.0             64              0        0  23.3   
3            1     89.0             66             23       94  28.1   
4            0    137.0             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
X=df.drop(['Outcome'],axis=1)
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35        0  33.6   
1            1     85.0             66             29        0  26.6   
2            8    183.0             64              0        0  23.3   
3            1     89.0             66             23       94  28.1   
4            0    137.0             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [8]:
y=df.Outcome
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=.2,random_state=33)

In [10]:
from sklearn.ensemble import RandomForestClassifier
r_cl=RandomForestClassifier(n_estimators=10).fit(X_train,y_train)
prediction=r_cl.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,prediction))


[[85 14]
 [26 29]]


In [12]:
print(accuracy_score(y_test,prediction))


0.7402597402597403


In [13]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.77      0.86      0.81        99
           1       0.67      0.53      0.59        55

    accuracy                           0.74       154
   macro avg       0.72      0.69      0.70       154
weighted avg       0.73      0.74      0.73       154



## RandomizedSearchCV

In [14]:
##Randomly select for finding hyperparams 
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
model=RandomForestClassifier()

In [15]:
[int(x) for x in np.linspace(start=200,stop=2000,num=10)]

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]

In [16]:

# number of trees in random forest
n_estimators=[int(x) for x in np.linspace(start=100,stop=2000,num=10)]
#number of features to consider at every split
max_features=["auto", "sqrt", "log2"]
##max number of level in tree
max_depth=[int(x) for x in np.linspace(10,1000,10)]
##minimum number of sample to split a node
min_samples_split=[1,2,3,4,5,7,9]
#minimum number of samples to split a each leaf node
min_samples_leaf=[1,2,4,6,8]
#create random grid
random_grid={
    "n_estimators":n_estimators,
    "max_features":max_features,
    "max_depth":max_depth,
    "min_samples_split":min_samples_split,
    "min_samples_leaf":min_samples_leaf,
    'criterion':['gini', "entropy"]
    
}

In [17]:
randm_cv=RandomizedSearchCV(estimator=RandomForestClassifier(),param_distributions=random_grid,n_iter=100,cv=3,random_state=100,n_jobs=-1)
randm_cv.fit(X_train,y_train)


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [1, 2, 3, 4, 5, 7,
                                                              9],
                                        'n_estimators': [100, 311, 522, 733,
                                                         944, 1155, 1366, 1577,
                                                         1788, 2000]},
                   r

In [18]:
randm_cv.best_params_

{'n_estimators': 733,
 'min_samples_split': 9,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 340,
 'criterion': 'gini'}

In [19]:
best_random_grid=randm_cv.best_estimator_

In [20]:
predicton_randomgrid=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,predicton_randomgrid))
print(accuracy_score(y_test,predicton_randomgrid))

[[85 14]
 [24 31]]
0.7532467532467533


## GridsearcCV

In [21]:
from sklearn.model_selection import GridSearchCV
params={
    "n_estimators":[randm_cv.best_params_['n_estimators']+200,
                   randm_cv.best_params_['n_estimators']-100,
                   randm_cv.best_params_['n_estimators'],
                   randm_cv.best_params_['n_estimators']+100,
                   randm_cv.best_params_['n_estimators']+200],
    "max_features":[randm_cv.best_params_['max_features']],
    "max_depth":[randm_cv.best_params_['max_depth']],
    "min_samples_split":[randm_cv.best_params_['min_samples_split']+2,
                         randm_cv.best_params_['min_samples_split']+1,
                         randm_cv.best_params_['min_samples_split']-2,
                         randm_cv.best_params_['min_samples_split']-1],
    "min_samples_leaf":[randm_cv.best_params_['min_samples_leaf'],
                        randm_cv.best_params_['min_samples_leaf']+2,
                        randm_cv.best_params_['min_samples_leaf']+4],
    'criterion':[randm_cv.best_params_['criterion']]
         }
print(params)

{'n_estimators': [933, 633, 733, 833, 933], 'max_features': ['auto'], 'max_depth': [340], 'min_samples_split': [11, 10, 7, 8], 'min_samples_leaf': [1, 3, 5], 'criterion': ['gini']}


In [22]:
5*1*1*4*3*1#iteration we should take

60

In [23]:
gcv=GridSearchCV(estimator=RandomForestClassifier(),param_grid=params,cv=10,n_jobs=-1,verbose=2)
gcv.fit(X_train,y_train)

Fitting 10 folds for each of 60 candidates, totalling 600 fits


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [340],
                         'max_features': ['auto'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [11, 10, 7, 8],
                         'n_estimators': [933, 633, 733, 833, 933]},
             verbose=2)

In [24]:
gcv.best_params_

{'criterion': 'gini',
 'max_depth': 340,
 'max_features': 'auto',
 'min_samples_leaf': 5,
 'min_samples_split': 10,
 'n_estimators': 633}

In [25]:
best_grid_cv=gcv.best_estimator_

In [26]:
gcv_prediction=best_grid_cv.predict(X_test)

In [27]:
print(confusion_matrix(y_test,gcv_prediction))

[[87 12]
 [26 29]]


In [28]:
print(accuracy_score(y_test,gcv_prediction))

0.7532467532467533


## Baysian Optimization

In [29]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials

In [30]:
space={
    'criterion':hp.choice('criterion',['entropy','gini']),
    'max_depth':hp.quniform('max_depth',10,1200,10),
    'max_features':hp.choice('max_features',['auto','sqrt','log2',None]),
    'min_samples_leaf':hp.uniform('min_samples_leaf',0,0.5),
    'min_samples_split':hp.uniform('min_samples_split',0,3),
    'n_estimators':hp.choice('n_estimators',[10,50,300,750,1000])
    }
space

{'criterion': <hyperopt.pyll.base.Apply at 0x220270bcdf0>,
 'max_depth': <hyperopt.pyll.base.Apply at 0x220270bcf70>,
 'max_features': <hyperopt.pyll.base.Apply at 0x220270c0040>,
 'min_samples_leaf': <hyperopt.pyll.base.Apply at 0x220270c0220>,
 'min_samples_split': <hyperopt.pyll.base.Apply at 0x220270c0370>,
 'n_estimators': <hyperopt.pyll.base.Apply at 0x220270c0490>}

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
space['criterion']

In [33]:
from statistics import mean
def objective(space):
    model3=RandomForestClassifier(criterion=space['criterion'],max_depth=space['max_depth'],max_features=space['max_features'],min_samples_leaf=space['min_samples_leaf'],min_samples_split=space['min_samples_split'],n_estimators=space['n_estimators'])
    print(model3)
    accuracy= cross_val_score(model3,X_train,y_train,cv=5).mean()
    print(accuracy)
    #WE AIM TO Maximise accuracy therefore we return it as negative value
    return{'loss': -accuracy,'status': STATUS_OK}
objective(space)

RandomForestClassifier(criterion=<hyperopt.pyll.base.Apply object at 0x00000220270BCDF0>,
                       max_depth=<hyperopt.pyll.base.Apply object at 0x00000220270BCF70>,
                       max_features=<hyperopt.pyll.base.Apply object at 0x00000220270C0040>,
                       min_samples_leaf=<hyperopt.pyll.base.Apply object at 0x00000220270C0220>,
                       min_samples_split=<hyperopt.pyll.base.Apply object at 0x00000220270C0370>,
                       n_estimators=<hyperopt.pyll.base.Apply object at 0x00000220270C0490>)
nan


{'loss': nan, 'status': 'ok'}

In [34]:
from sklearn.model_selection import cross_val_score
trial=Trials()
best= fmin(fn=objective,
         space=space,
         algo=tpe.suggest,
         max_evals=80,
         trials=trial)
best

RandomForestClassifier(criterion='entropy', max_depth=340.0,                                                           
                       max_features='log2',
                       min_samples_leaf=0.07119881409639867,
                       min_samples_split=2.1902793638334184, n_estimators=300)
nan                                                                                                                    
RandomForestClassifier(criterion='entropy', max_depth=1100.0, max_features=None,                                       
                       min_samples_leaf=0.2550212253515461,
                       min_samples_split=1.67614596205745, n_estimators=10)
nan                                                                                                                    
RandomForestClassifier(max_depth=890.0, min_samples_leaf=0.09743647335825345,                                          
                       min_samples_split=2.9427680593499645, n_estimators=750)
n

RandomForestClassifier(max_depth=380.0, max_features='log2',                                                           
                       min_samples_leaf=0.452419951901624,
                       min_samples_split=0.6768092873244675, n_estimators=750)
0.6530987604958016                                                                                                     
RandomForestClassifier(criterion='entropy', max_depth=1030.0,                                                          
                       max_features='sqrt', min_samples_leaf=0.4512415935522819,
                       min_samples_split=1.4517367554103313, n_estimators=50)
nan                                                                                                                    
RandomForestClassifier(max_depth=490.0, max_features='sqrt',                                                           
                       min_samples_leaf=0.24040942841352103,
                       min_samples_split=2

0.7378381980541118                                                                                                     
RandomForestClassifier(max_depth=1120.0, max_features='sqrt',                                                          
                       min_samples_leaf=0.34015220087915415,
                       min_samples_split=1.7735336775789619, n_estimators=50)
nan                                                                                                                    
RandomForestClassifier(max_depth=160.0, min_samples_leaf=0.24830390597084273,                                          
                       min_samples_split=2.512533972480518, n_estimators=50)
nan                                                                                                                    
RandomForestClassifier(criterion='entropy', max_depth=1030.0,                                                          
                       max_features='log2',
                    

nan                                                                                                                    
RandomForestClassifier(max_depth=960.0, max_features=None,                                                             
                       min_samples_leaf=0.0003916737809637888,
                       min_samples_split=2.509230177413948, n_estimators=50)
nan                                                                                                                    
RandomForestClassifier(max_depth=960.0, max_features=None,                                                             
                       min_samples_leaf=0.001136754332726586,
                       min_samples_split=2.733461334375741, n_estimators=50)
nan                                                                                                                    
RandomForestClassifier(max_depth=860.0, max_features=None,                                                             
 

{'criterion': 0,
 'max_depth': 990.0,
 'max_features': 2,
 'min_samples_leaf': 0.09955766096765534,
 'min_samples_split': 0.08978536183584429,
 'n_estimators': 3}

In [35]:
crit={0:'entropy',1:'gini'}
features={ 0:'auto',1:'sqrt',2:'log2',3:None}
estimators={0:10,1:50,2:300,3:750,4:1000}


In [36]:
estimators[best['n_estimators']]

750

In [37]:
model4=RandomForestClassifier(criterion=crit[best['criterion']],max_depth=best['max_depth'],max_features=features[best['max_features']],min_samples_leaf=best['min_samples_leaf'],min_samples_split=best['min_samples_split'],n_estimators=estimators[best['n_estimators']])

In [38]:
model4.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=990.0,
                       max_features='log2',
                       min_samples_leaf=0.09955766096765534,
                       min_samples_split=0.08978536183584429, n_estimators=750)

In [39]:
predic_forest=model4.predict(X_test)
print(confusion_matrix(predic_forest,y_test))
print(accuracy_score(predic_forest,y_test))

[[90 34]
 [ 9 21]]
0.7207792207792207


## Genetic ALgotiyhm

In [44]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [45]:
# number of trees in random forest
n_estimators=[int(x) for x in np.linspace(start=100,stop=2000,num=10)]
#number of features to consider at every split
max_features=["auto", "sqrt", "log2"]
##max number of level in tree
max_depth=[int(x) for x in np.linspace(10,1000,10)]
##minimum number of sample to split a node
min_samples_split=[1,2,3,4,5,7,9]
#minimum number of samples to split a each leaf node
min_samples_leaf=[1,2,4,6,8]
#create random grid
param={
    "n_estimators":n_estimators,
    "max_features":max_features,
    "max_depth":max_depth,
    "min_samples_split":min_samples_split,
    "min_samples_leaf":min_samples_leaf,
    'criterion':['gini', "entropy"]
    
}

In [50]:
!pip install tpot

In [51]:
from tpot import TPOTClassifier

In [52]:
#k=sklearn.ensemble.RandomForestClassifier

In [60]:
TPOT_classifier=TPOTClassifier(generations=5,population_size=24,offspring_size=12,verbosity=2,
                               config_dict={'sklearn.ensemble.RandomForestClassifier':param},
                               early_stop=12,cv=4,scoring='accuracy')


In [ ]:
TPOT_classifier.fit(X_train,y_train)
accuracy=TPOT_classifier.score(X_test, y_test)
print(accuracy)

### Optimize hyperparameters of the model using Optuna

In [64]:
import optuna
import sklearn.svm


In [81]:
def objective(trial):
    classifier = trial.suggest_categorical('classifier', ['RandomForest', 'SVC'])
    if classifier=='RandomForest':
        n_estimators=trial.suggest_int('n_estimators',200,2000,10)
        max_depth=int(trial.suggest_float('max_depth',10,100,log=True))
        
        clf=RandomForestClassifier(n_estimators=n_estimators,max_depth=max_depth)
    else:
        c=trial.suggest_float('svc_c',1e-10,1e10,log=True)
        clf = sklearn.svm.SVC(C=c, gamma='auto')
    return sklearn.model_selection.cross_val_score(clf,X_train,y_train,n_jobs=-1,cv=3).mean()
    

In [82]:
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)
trial = study.best_trial
print('Accuracy: {}'.format(trial.value))
print("Best hyperparameters: {}".format(trial.params))

[I 2021-11-08 12:43:59,208] A new study created in memory with name: no-name-4fbdf9ff-d8db-4d06-bde8-53ac3d8fd36c
[I 2021-11-08 12:44:34,380] Trial 0 finished with value: 0.6530926191614858 and parameters: {'classifier': 'SVC', 'svc_c': 9.46070142173073}. Best is trial 0 with value: 0.6530926191614858.
[I 2021-11-08 12:44:43,786] Trial 1 finished with value: 0.7638769328869759 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1200, 'max_depth': 51.64832586503327}. Best is trial 1 with value: 0.7638769328869759.
[I 2021-11-08 12:44:52,398] Trial 2 finished with value: 0.7703969392635103 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1180, 'max_depth': 91.13344277392265}. Best is trial 2 with value: 0.7703969392635103.
[I 2021-11-08 12:44:52,604] Trial 3 finished with value: 0.6530926191614858 and parameters: {'classifier': 'SVC', 'svc_c': 35.96738777888134}. Best is trial 2 with value: 0.7703969392635103.
[I 2021-11-08 12:44:57,144] Trial 4 finished with val

[I 2021-11-08 12:47:16,685] Trial 35 finished with value: 0.767144906743185 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1800, 'max_depth': 19.33085524730398}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:47:20,738] Trial 36 finished with value: 0.7622668579626972 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1240, 'max_depth': 32.75926423701165}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:47:20,835] Trial 37 finished with value: 0.6530926191614858 and parameters: {'classifier': 'SVC', 'svc_c': 2480301762.958945}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:47:25,908] Trial 38 finished with value: 0.7622668579626972 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1510, 'max_depth': 47.453250345703175}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:47:25,979] Trial 39 finished with value: 0.6530926191614858 and parameters: {'classifier': 'SVC', 'svc_c': 1.0

[I 2021-11-08 12:50:25,646] Trial 70 finished with value: 0.7687948350071737 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1150, 'max_depth': 11.007660243133806}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:50:31,575] Trial 71 finished with value: 0.767144906743185 and parameters: {'classifier': 'RandomForest', 'n_estimators': 1040, 'max_depth': 34.49397514558973}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:50:34,962] Trial 72 finished with value: 0.7638769328869759 and parameters: {'classifier': 'RandomForest', 'n_estimators': 690, 'max_depth': 15.367384582614934}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:50:39,469] Trial 73 finished with value: 0.772030926191615 and parameters: {'classifier': 'RandomForest', 'n_estimators': 940, 'max_depth': 14.434163146046506}. Best is trial 4 with value: 0.7785589032360912.
[I 2021-11-08 12:50:44,209] Trial 74 finished with value: 0.772038896859557 and parameters: {

Accuracy: 0.7785589032360912
Best hyperparameters: {'classifier': 'RandomForest', 'n_estimators': 920, 'max_depth': 42.818421203225114}


In [93]:
#optuna.visualization.plot_contour(study,params=['n_estimators','max_depth'])

In [92]:
trial.params

{'classifier': 'RandomForest',
 'n_estimators': 920,
 'max_depth': 42.818421203225114}

In [94]:
study.best_params

{'classifier': 'RandomForest',
 'n_estimators': 920,
 'max_depth': 42.818421203225114}

In [97]:
rf=RandomForestClassifier(n_estimators=920,max_depth= 42.818421203225114)
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=42.818421203225114, n_estimators=920)

In [98]:
y_pred=rf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85 14]
 [23 32]]
0.7597402597402597
              precision    recall  f1-score   support

           0       0.79      0.86      0.82        99
           1       0.70      0.58      0.63        55

    accuracy                           0.76       154
   macro avg       0.74      0.72      0.73       154
weighted avg       0.75      0.76      0.75       154

